spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-microk8s
          ports:
            - containerPort: 80
            - containerPort: 443
            - name: tcp-proxy-50051
              containerPort: 50051
              hostPort: 50051
              protocol: TCP